(function(t,v,m,p,l){t[v]=t[v]||{};for(t[v].q=t[v].q||[];l<p.length;)m(p[l++],t[v])})(window,"extole",function(t,v){v[t]=v[t]||function(){v.q.push([t,arguments])}},["log"],0);
extole.define||function(){function t(e){e=l(e);return c[e]}function v(e,n){extole.log("error","[REQUIRE] "+e,n)}function m(e,n){if(e.length)for(var u=0;u<e.length;u++)n(e[u],u);else for(u in e)Object.prototype.hasOwnProperty.call(e,u)&&n(e[u],u)}function p(e,n){let u=[];m(e,function(w,z){u[z]=n(w,z)});return u}function l(e){return"string"!==typeof e?e:/origin-\d/.test(e)?e.substring(e.indexOf("type=")).replace(/version=\d+:/,""):e}function r(e){let n=e.split("/").slice(-1)[0],u=n.length;m(n.toLowerCase(),
function(w){u+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(w)});return e.replace("origin","origin-"+u%8)}function h(e){let n=/^extole-creatives:/.test(e),u=/^extole-media:/.test(e),w=/^core-root:\/\//.test(e),z=/^extole-assets:/.test(e),G=/origin\./.test(e),C=/^http:/.test(e),x=/^https:/.test(e);return n?(e=e.slice(17),h("extole-assets:/core-modules/"+e)):z?(e=e.slice(14),h("extole-media:/assets/"+e)):u?(e=e.slice(13),e=extole.CORE_ROOT+e,h(e)):w?(e=e.slice(12),e=extole.CORE_ROOT+e,h(e)):G?
(e=r(e),e+="?site="+window.location.hostname,h(e)):C?(e=e.slice(5),h(e)):x?(e=e.slice(6),h(e)):e}function f(){}function g(){let e="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),n=document.createElement("script");this.useInteractive=n.attachEvent&&!(n.attachEvent.toString&&0>n.attachEvent.toString().indexOf("[native code"))&&!e}function d(){m(c,function(e){e._fetched?e._defined||e.define():e.fetch()})}function a(e,n,u,w,z){if("$config"!=e){var G=t(e),C=G||new f;G||(G=
l(e),c[G]=C);e&&n&&(C._fetched=!0);C.start=C.start||(new Date).getTime();C.url=C.url||e;C.dependencies=C.dependencies||n;C.config=C.config||w;C.definedCallback=C.definedCallback||u;C.isRequire=C.isRequire||z}}function b(e,n,u,w){e instanceof Array&&(w=u,u=n,n=e,e=void 0);k.addDefine({url:e,dependencies:n,definedCallback:u,config:w})}let c={},k;f.prototype={getUnresolvedDependencies:function(){let e=[];m(this.dependencies,function(n){"$config"!=n&&(n=t(n),(!n||n&&!n._defined)&&e.push(n))});return e},
getDependencies:function(){let e=this,n=[];m(e.dependencies,function(u){u="$config"==u?e.config||null:t(u).definition||null;n.push(u)});return n},define:function(){function e(z){n.definedCallback=void 0;n.definition=z;n.end=(new Date).getTime();n.timeToDefine=n.end-n.start;n._defining=!1;n._defined=!0;setTimeout(d,1)}let n=this;n.defineStartTime=n.defineStartTime||(new Date).getTime();if(!n._defining&&!n._defined&&n.dependencies)if(n._defining=!0,0<n.getUnresolvedDependencies().length)n._defining=
!1;else{var u=n.getDependencies(),w={isAsync:!1,async:function(){n.isAsync=!0;w.isAsync=n.isAsync;return function(z){e(z)}}};(function(){if(n.definedCallback){var z=n.definedCallback;z=z&&z.apply(w,u);w.isAsync||e(z)}else e(!0)})()}},fetch:function(){let e=this;e._fetching||e._fetched||(e.url?(e._fetching=!0,e.startFetchTime=(new Date).getTime(),k.loadModule(e.url,function(){e._fetching=!1;e.endFetchTime=(new Date).getTime();e.timeToFetch=e.endFetchTime-e.startFetchTime;e._fetched=!0;e.define()})):
v("Tried to fetch a module without a url - dependencies: "+e.dependencies+" definedCallback: "+(e.definedCallback?"exists":"null")+" config: "+e.config))}};g.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(k.interactiveScript&&"interactive"==k.interactiveScript.readyState)return k.interactiveScript;let e=document.getElementsByTagName("head")[0].getElementsByTagName("script"),n;for(let u=e.length-1;0<=u;u--){let w=this.getScriptDataUrl(e[u]);
e[u]&&"interactive"==e[u].readyState&&w&&(n=e[u])}return n},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(e){return e.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(e,n){e.setAttribute(this.scriptUrlAttributeName,n)},attachOnLoad:function(e,n){function u(G){let C=e.readyState;if(w&&"interactive"==C)this.interactiveScript=e;else if("load"===G.type||z.test(C))w?e.detachEvent("onreadystatechange",u):e.removeEventListener("load",u,!1),n(G)}n=n||function(){};
let w=this.useInteractive,z="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;w?e.attachEvent("onreadystatechange",u):e.addEventListener("load",u,!1)},defineTimeout:null,addDefine:function(e){if(e.url)e.url=h(e.url);else{var n=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&n&&(n=this.getScriptDataUrl(n),e.url=n,this.interactiveScript=null)}e.dependencies=p(e.dependencies,h);this.useInteractive&&!e.url&&v("defines should not be missing a url in ie.");
this.defineQueue.push(e);this.defineTimeout&&clearTimeout(this.defineTimeout);let u=this;this.defineTimeout=setTimeout(function(){u.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){let e=[],n;for(;n=this.defineQueue.shift();){let u=[];m(n.dependencies,function(w){w&&u.push(w)});n.url&&t(n.url);n.url||e.push("deps "+n.dependencies);m(u,function(w){a(w)});a(n.url,u,n.definedCallback,n.config,n.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(d,
1)},loadModule:function(e,n){let u=document.createElement("script");u.async=!0;u.crossOrigin="anonymous";this.setScriptDataUrl(u,e);let w=this,z;this.attachOnLoad(u,function(){clearTimeout(z);if(!w.useInteractive){let C;for(let x=w.defineQueue.length-1;0<=x;x--)w.defineQueue[x].url||(C&&v("Multiple anonymous modules loaded in one script - "+e),C=w.defineQueue[x]);C&&(C.url=e)}w.intakeDefines();n&&n(null)});u.src=e;z=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:e})},2E3);this.currentlyAddingScript=u;let G=document.getElementsByTagName("head")[0]||document.head;G?G.appendChild(u):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+e,void 0);this.currentlyAddingScript=void 0}};k=new g;b.getModule=function(e){return t(e)};let q=0;extole.define=b;extole.require=function(e,n){var u=k,w=u.addDefine;q++;w.call(u,{url:"anonymous_"+q,dependencies:e,definedCallback:n,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:h}});
setTimeout(function(){let e=!1,n=[];m(c,function(u){u._defined||(e=!0);n.push({defineStartTime:u.defineStartTime,dependencies:u.dependencies,end:u.end,start:u.start,isRequire:u.isRequire,timeToDefine:u.timeToDefine,url:u.url,_defined:u._defined,_defining:u._defining,_fetched:u._fetched})});e&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(n)+"###")},7E3)}();
(function(){(function(){try{window.extole&&(window.extole.suppressLog=!0),extole.LOG_EXCLUDE_REGEX=/Scanned for 3000 ms searching for zone element id/,extole.createZonePrehandler=function(t,v){if("referral_page"===t.name){const m=window.location.href,p=m.split("/"),l=document.querySelector("#"+t.element_id);v.referer_url=m;v.url_country=3<p.length?p[3]:null;l||(console.log("[Extole] Couldn't find element with id "+t.element_id),console.log("[Extole] Searching for element with id all-products"),document.querySelector("#all-products")?
(console.log("[Extole] Found element with id all-products. Replacing element_id "+t.element_id+" with all-products"),t.element_id="all-products"):console.log("[Extole] Couldn't find element with id all-products"))}}}catch(t){extole.log("error","Error executing extended core javascript. Message: "+t.message+" Stack: "+t.stack)}})()})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js"],function(t,v){let m=/^extole_(?!zone)/,p=/^extole_zone_/;return new function(){function l(f){let g={};f=f||h;t.each(f,function(d,a){m.test(a)&&(a=a.replace(m,""),g[a]=d)});return g}function r(){let f,g,d={};this.withName=function(a){f=a;return this};this.withElementId=
function(a){g=a;return this};this.withData=function(a,b){d[a]=b;return this};this.build=function(){let a={};f&&(a.name=f);g&&(a.elementId=g);d&&(a.data=d);return a}}let h=v.deserialize(location.search);this.parseUriZoneDefinition=function(f){let g=new r,d,a;f=f||h;d=l(f);t.each(d,function(b,c){g.withData(c,b)});t.each(f,function(b,c){p.test(c)&&(c=c.replace(p,""),"name"===c?(a=!0,g.withName(b)):"element_id"===c?g.withElementId(b):g.withData(c,b))});return a?g.build():null};this.parseGlobalZoneParameters=
l}});(function(t,v,m,p,l){t[v]=t[v]||{};for(t[v].q=t[v].q||[];l<p.length;)m(p[l++],t[v])})(window,"extole",function(t,v){v[t]=v[t]||function(){v.q.push([t,arguments])}},["createZone","log"],0);
(function(){var t=[{name:"MOO Referral Program",programDomain:"refer.moo.com",sitePatterns:"refer.moo.com my.extole.com *.my.extole.com moo.com *.moo.com staging.moo.com *.staging.moo.com testing9.office.moo.com *.testing9.office.moo.com moocrews.com *.moocrews.com".split(" "),siteRegexPatterns:"refer\\.moo\\.com\\.?$ my\\.extole\\.com\\.?$ .*\\.my\\.extole\\.com\\.?$ moo\\.com\\.?$ .*\\.moo\\.com\\.?$ staging\\.moo\\.com\\.?$ .*\\.staging\\.moo\\.com\\.?$ testing9\\.office\\.moo\\.com\\.?$ .*\\.testing9\\.office\\.moo\\.com\\.?$ moocrews\\.com\\.?$ .*\\.moocrews\\.com\\.?$".split(" ")}];extole.CORE_ROOT=
"https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545";extole.CORE_CONFIG={backendTargetingEnabled:!0,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!1,isAccessTokenIncludedInResponseEnabled:!0,cookieConsentPolicy:"COOKIE_CONSENT_OR_SESSION_COOKIE",cookieDomainPolicy:"SUBDOMAIN",cookieConsentEnabled:!1};extole.CLIENT_ID="1816143665";extole.BUILD_DATE="1772721809370";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||
/[?&]extole_debug=true(&|$)/.test(location.search);extole.CURRENT_PROGRAM_DOMAIN="__CURRENT_PROGRAM_DOMAIN__";extole.PROGRAM=function(){function v(d,a){d=Error.call(this,d);this.name="ExtoleError";this.message=d.message;this.stack=d.stack;this.code=a}function m(d,a){if(d.length)for(var b=0;b<d.length;b++)a(d[b],b);else for(b in d)Object.prototype.hasOwnProperty.call(d,b)&&a(d[b],b)}function p(d,a){let b=[];m(d,function(c){(c=a(c))&&(b[b.length]=c)});return b}function l(d,a){a=a||[];let b=!1;m(a,function(c){(new RegExp(c)).test(d)&&
(b=!0)});return b}function r(d){let a=window.location.hostname;return p(d,function(b){if(l(a,b.siteRegexPatterns))return b})}function h(d,a){let b=null;m(d,function(c){c.programDomain===a&&(b=c)});return b}function f(){extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ajax.js"],function(d,a){var b=extole.CORE_ROOT;d=b.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,
"$1")+"/_extole_core.gif"+d.serialize({core_root:b,referer:window.location.hostname});a({url:d})})}v.prototype=Error();v.prototype.constructor=v;let g;"__CURRENT_PROGRAM_DOMAIN__"!==extole.CURRENT_PROGRAM_DOMAIN&&(g=h(t,extole.CURRENT_PROGRAM_DOMAIN));if(!g){let d=r(t);g=d[0];if(!g)throw f(),new v("No program domain is configured for hostname: "+window.location.hostname+" unable to use Extole API","site_configuration_error");1<d.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+
" programs: "+JSON.stringify(d))}return g}();extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js","create-zone-executor"],function(v,m,p){function l(){function d(b){let c=b[0];"function"===typeof a[c]?(a[c].apply(null,b[1]),extole.q.history.push({name:b[0],args:b[1],timestamp:Date.now(),stack:Error().stack})):m.warn("Unable to execute method: "+
c+", it is not implemented.")}let a={log:function(){let b=Array.prototype.slice.call(arguments),c=b[0];"function"===typeof m[c]&&m[c].apply(null,b.slice(1))},createZone:p.initiateExecution};for(extole.q.history=[];extole.q.length;)d(extole.q.shift());extole.q.push=d}function r(){extole.require(["extole-uri-parser"],function(d){let a=v.deserialize(location.search);(d=d.parseUriZoneDefinition(a))&&extole.createZone(d)})}function h(d){d=d||function(){};let a=v.deserialize(location.search).jwt;a?extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ajax.js",
"https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/program.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/token-store.js"],function(b,c,k){c=c.getProtocol()+c.getProgramDomain()+"/api/v5/token";m.debug("Validating JWT from URL and fetching new access token");b({url:c,type:"POST",headers:{"Content-Type":"application/json","X-Extole-App":"javascript_sdk"},data:{jwt:a},complete:function(q){try{let e=
JSON.parse(q);e.access_token?(k.set(e.access_token),m.debug("JWT validation successful, new token stored")):m.warn("JWT validation response missing access_token")}catch(e){m.error("Error parsing JWT validation response: "+e.message)}d()},error:function(q,e){m.warn("JWT validation failed with status: "+e);d()},xhrFields:{withCredentials:!0},noAuthorizationHeader:!0})}):d()}function f(){let d;"function"===typeof window.onerror&&(d=window.onerror);let a=extole.PROGRAM.programDomain.split(".").join("\\."),
b=new RegExp("(http|https):\\/\\/"+a,"i");window.onerror=function(c,k,q,e,n){function u(C,x){if(null!==x&&"object"===typeof x){if(0<=w.indexOf(x))return;w.push(x)}return x}let w;if(d)try{d(c,k,q,e,n)}catch(C){}k=k||window.location.href||"no_source_or_location.href";n=n&&n.stack?n.stack:"no_error.stack";var z=new RegExp("^(http|https):\\/\\/("+a+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");let G=k.split("?")[0].split("#")[0];z=z.test(G);if(!z){let C=n+c;z=[/core-root:\/\//i,
/extole-creatives:/i,/extole-assets:/i,/extole-media:/i,/extole\.define\(/i,/extole\.require\(/i,/(?:^|\/)core\.js(?:[?#]|$)/i];b&&z.unshift(b);z=z.some(function(x){return x.test(C)})}if(z){let C={MESSAGE:c,SOURCE:k,LINE_NUMBER:q,COLUMN_NUMBER:e,STACK_TRACE:n};w=[];try{let x=JSON.stringify(C,u);extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(B){try{B.error("Unhandled exception",JSON.parse(x))}catch(A){B.error("Unhandled exception",
C)}})}catch(x){extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(B){B.error("Unhandled exception (stringify failed)",C)})}}}}function g(){extole._bootstrapped=!0;f();h(function(){l();r()})}extole.bootstrap=g;extole._bootstrapped||g();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(d){extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],
function(a){a.error("Error executing extended core javascript. Message : "+d.message+" Stack: "+d.stack)})}})})();
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ExtoleError.js",[],function(){function t(m,p,l,r){m=Error.call(this,m);this.name="ExtoleError";this.message=m.message||"no_message";this.stack=Error().stack;this.code=p||"extole_error";this.data=l||{};this.logLevel=0<=v.indexOf(r)?r:"error"}let v=["debug","info","warn","error"];t.prototype=Error();t.prototype.constructor=t;t.prototype.toString=function(){return this.name+" ["+this.logLevel+
"]: message: "+this.message+"; code: "+this.code+"; data: "+JSON.stringify(this.data,null,4)+"; stack trace: "+this.stack+";"};return t});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/type.js"],function(t,v){function m(l,r){let h;var f;if(l.length===Number(l.length))for(f=0;f<l.length;f++){if(h=r(l[f],f),!1===h)return!1}else for(f in l)if(Object.prototype.hasOwnProperty.call(l,
f)&&(h=r(l[f],f),!1===h))return!1}function p(l){if(!l||"object"!==typeof l&&!v.isPlainFunction(l))l={};for(let r=1;r<arguments.length;r++)if(v.isPlainObject(arguments[r]))for(let h in arguments[r]){let f=arguments[r][h];f!==l&&void 0!==f&&(v.isPlainObject(f)&&v.isPlainObject(l[h])?f=p(l[h],f):v.isArray(f)&&v.isArray(l[h])&&l[h].concat&&(f=l[h].concat(f)),l[h]=f)}return l}m.BREAK=!1;return{each:m,map:function(l,r){function h(d,a){g=[];m(d,function(b,c){g.push(a(b,c))})}function f(d,a){g={};m(d,function(b,
c){g[c]=a(b,c)})}let g;if(v.isArray(l))h(l,r);else if(v.isPlainObject(l))f(l,r);else throw new t(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return g},filter:function(l,r){function h(d,a){g=[];m(d,function(b,c){a(b,c)&&g.push(b)})}function f(d,a){g={};m(d,function(b,c){a(b,c)&&(g[c]=b)})}let g;if(v.isArray(l))h(l,r);else if(v.isPlainObject(l))f(l,r);else throw new t(l+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return g},merge:p,clone:function(l){return JSON.parse(JSON.stringify(l))},
flatten:function(l){function r(f,g){if(v.isPlainObject(f))m(f,function(d,a){let b=g.slice();b.push(a);r(d,b)});else{let d=g.join(".");h[d]=f}}if(!v.isPlainObject(l))return l;let h={};r(l,[]);return h},find:function(l,r){let h;m(l,function(f,g){if(r(f,g))return h=f,m.BREAK});return h},reverse:function(l){let r=[];if(!l||l.length!==Number(l.length))return l;for(let h=l.length-1;0<=h;h--)r.push(l[h]);return r},nashornToJs:function(l){let r;if(v.isPlainJs(l)||!l)return l;if(v.isJavaMap(l)){r={};for(let h in l)r[h]=
l[h]}else if(v.isNumber(l.length))r=[],m(l,function(h,f){r[f]=h});else return l;return r},intersection:function(l,r){let h=[];m(l,function(f){0>r.indexOf(f)||0<=h.indexOf(f)||h.push(f)});return h},difference:function(l,r){let h=[];m(l,function(f){0<=r.indexOf(f)||0<=h.indexOf(f)||h.push(f)});return h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(t){function v(h){try{return decodeURIComponent(h.replace(p," "))}catch(f){return t.info("** cookie.decode ** Cookie error for: "+h,{error:f,message:f.message,stack:f.stack,cookiePart:h}),""}}function m(h){h=v(h);return 0===h.indexOf('"')?h.slice(1,-1).replace(l,'"').replace(r,
"\\"):h}let p=/\+/g,l=/\\"/g,r=/\\\\/g;return function(h,f,g){if(void 0!==f){g=g||{};var d=document;h=encodeURIComponent(h);f=encodeURIComponent(f);if(g.expires){var a=g.expires;if(!a||!a.toUTCString){let b=new Date;b.setDate(b.getDate()+("number"===typeof a?a:0));a=b}a="; expires="+a.toUTCString()}else a="";return d.cookie=[h,"=",f,a,g.path?"; path="+g.path:"",g.domain?"; domain="+g.domain:"",g.samesite?"; samesite="+g.samesite:"","; secure"].join("")}a:{g=document.cookie?document.cookie.split("; "):
[];d=h?null:{};for(let b=0,c=g.length;b<c;b++)if(f=g[b].split("="),a=v(f[0]),!h)d[a]=m(f[1]);else if(h===a){g=m(f[1]);break a}g=d}return g}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/device-type.js",[],function(){function t(p){return v.test(p)}let v=RegExp("Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront","i"),m=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(Version\/\d+\.\d+\s)|Linux; U; Android/i;return{isMobile:t,isDesktop:function(p){return!t(p)},
isWebview:function(p){return m.test(p)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/dom.js",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(t){function v(d,a){return(a||document).querySelectorAll(d)}function m(d,a){return v(d,a)[0]}function p(d,a){function b(){clearTimeout(k);a(c);r.removeListener(c,"load",b)}a=a||function(){};if(g[d]||!d)return a(g[d]),g[d]||null;g[d]=document.createElement("link");let c=
g[d];h.setAttribute(c,"rel","stylesheet");h.setAttribute(c,"href",d);f.append(m("head"),c);r.addListener(c,"load",b);let k=setTimeout(function(){t.warn("Load timeout reached for stylesheet: ",{url:d});b()},5E3);return c}let l={each:function(d,a){let b;var c;if(d.length===Number(d.length))for(c=0;c<d.length;c++){if(b=a(d[c],c),!1===b)return!1}else for(c in d)if(Object.prototype.hasOwnProperty.call(d,c)&&(b=a(d[c],c),!1===b))return!1},extend:function(){let d,a;let b,c,k=arguments[0]||{},q=1,e=arguments.length,
n=!1,u=this.extend;"boolean"===typeof k&&(n=k,k=arguments[1]||{},q=2);for("object"===typeof k||this.isFunction(k)||(k={});q<e;q++)if(d=arguments[q],null!==d)for(a in d){var w=k[a];b=d[a];k!==b&&(n&&b&&(this.isPlainObject(b)||(c=this.isArray(b)))?(c?(c=!1,w=w&&this.isArray(w)?w:[]):w=w&&this.isPlainObject(w)?w:{},k[a]=u(n,w,b)):void 0!==b&&(k[a]=b))}return k},isFunction:function(d){return d&&"function"===typeof d&&d.call&&d.apply},isPlainObject:function(d){if("[object Object]"!==String(d)||d.nodeType||
d.window&&d.window==d)return!1;try{if(d.constructor&&!Object.prototype.hasOwnProperty.call(d.constructor.prototype,"isPrototypeOf"))return!1}catch(a){return!1}return!0},isArray:function(d){return d instanceof Array}};l.each.BREAK=!1;let r=function(){function d(q,e,n){let u=[];for(let w=0;w<k.length;w++){let z=k[w];z.element==q&&z.eventType==e&&z.listener==n&&u.push({index:w,eventListener:z})}return u}function a(q){let e=[];for(let n=0;n<k.length;n++){let u=k[n];u.element===q&&e.push(u)}return e}function b(q){this.originalEvent=
q;this.type=q.type;this.keyCode=q.keyCode;this.target=q.srcElement?q.srcElement:q.target}function c(q,e,n){n=d(q,e,n);0>=n.length?t.info("events.remove - Couldn't find exiting event listener for type \""+e+'" listener on element '+q):l.each(n,function(u){let w=u.index;u=u.eventListener;q.removeEventListener?q.removeEventListener(e,u.listenerWrapper,!1):q.detachEvent("on"+e,u.listenerWrapper);k.splice(w,1)})}let k=[];b.prototype={preventDefault:function(){let q=this.originalEvent;q.preventDefault?
q.preventDefault():q.returnValue=!1},stopPropagation:function(){let q=this.originalEvent;q.stopPropagation&&q.stopPropagation();q.cancelBubble=!0}};return{addListener:function(q,e,n){function u(z){w&&(z=window.event);return n.call(q,new b(z))}if(0<d(q,e,n).length)t.warn("events.add - Listener already exists for event "+e+" on element "+q);else{var w=!q.addEventListener;k.push({element:q,eventType:e,listener:n,listenerWrapper:u});q.addEventListener?q.addEventListener(e,u,!1):q.attachEvent("on"+e,u)}},
triggerEvent:function(q,e,n){let u=document.createEvent("Event");n=l.extend({},n);let w=!1===!n.bubbles,z=!0===n.cancelable;delete n.bubbles;delete n.cancelable;u.initEvent(e,w,z);l.extend(u,n);q.dispatchEvent(u)},removeListener:c,clearListeners:function(q){q=a(q);l.each(q,function(e){c(e.element,e.eventType,e.listener)})}}}(),h=function(){function d(b){b=b.className;let c={};if(!b)return c;l.each(b.split(" "),function(k){c[k]=1});return c}function a(b){let c="";l.each(b,function(k,q){c+=" "+q});
return c.slice(1)}return{setAttribute:function(b,c,k){b.setAttribute(c,k);b[c]=k},getAttribute:function(b,c){return b.getAttribute(c)},removeAttribute:function(b,c){return b.removeAttribute(c)},addClass:function(b,c){let k=d(b);k[c]||(k[c]=1,b.className=a(k))},removeClass:function(b,c){let k=d(b);delete k[c];b.className=a(k)},getClassNames:function(b){return b.className.split(" ")}}}(),f=function(){function d(b){let c=document.createDocumentFragment(),k=document.createElement("div");k.innerHTML=b;
l.each(k.childNodes,function(q){1==q.nodeType&&c.appendChild(q)});return c}function a(b){let c;l.each(b.childNodes,function(k){if(!c&&1==k.nodeType)return c=k,l.each.BREAK});return c}return{prepend:function(b,c){let k=a(b),q=c;"string"===typeof c&&(q=d(c));k?b.insertBefore(q,k):b.appendChild(q)},append:function(b,c){let k=c;"string"===typeof c&&(k=d(c));b.appendChild(k)}}}(),g={};return{addEventListener:r.addListener,removeEventListener:r.removeListener,triggerEvent:r.triggerEvent,clearEventListeners:r.clearListeners,
getAttribute:h.getAttribute,setAttribute:h.setAttribute,removeAttribute:h.removeAttribute,addClass:h.addClass,removeClass:h.removeClass,getClassNames:h.getClassNames,prepend:f.prepend,append:f.append,query:v,queryFirst:m,isVisible:function(d,a){return!!(m(d,a)||{}).offsetParent},injectStylesheet:p,injectStylesheets:function(d,a){function b(q){--c||a(k)}a=a||function(){};if(0===d.length)a();else{var c=0,k=[];l.each(d,function(q){c++;setTimeout(function(){k.push(p(q,b))},1)})}},scrollIntoViewIfNeeded:function(d,
a){function b(w,z){return{start:w,length:z,end:w+z}}function c(w,z){return!1===a||z.start<w.end&&w.start<z.end?Math.min(w.start,Math.max(z.start,w.end-z.length)):(w.start+w.end-z.length)/2}function k(w,z){return{x:w,y:z,translate:function(G,C){return k(w+G,z+C)}}}function q(w,z){for(;w;)z=z.translate(w.offsetLeft,w.offsetTop),w=w.offsetParent;return z}let e=q(d,k(0,0)),n=k(d.offsetWidth,d.offsetHeight);d=d.parentNode;let u;for(;d instanceof HTMLElement;)u=q(d,k(d.clientLeft,d.clientTop)),d.scrollLeft=
c(b(e.x-u.x,n.x),b(d.scrollLeft,d.clientWidth)),d.scrollTop=c(b(e.y-u.y,n.y),b(d.scrollTop,d.clientHeight)),e=e.translate(-d.scrollLeft,-d.scrollTop),d=d.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/event-bus.js",[],function(){function t(){function p(h,f,g,d){if(!g)return!0;if("object"===typeof g){for(let a in g)h[f].apply(h,[a,g[a]].concat(d));return!1}if(r.test(g)){g=g.split(r);for(let a=0,b=g.length;a<b;a++)h[f].apply(h,[g[a]].concat(d));return!1}return!0}function l(h,f){let g,d=-1,a=h.length,b=f[0],c=f[1],k=f[2];switch(f.length){case 0:for(;++d<a;)(g=h[d]).callback.call(g.ctx);break;
case 1:for(;++d<a;)(g=h[d]).callback.call(g.ctx,b);break;case 2:for(;++d<a;)(g=h[d]).callback.call(g.ctx,b,c);break;case 3:for(;++d<a;)(g=h[d]).callback.call(g.ctx,b,c,k);break;default:for(;++d<a;)(g=h[d]).callback.apply(g.ctx,f)}}this._events={};let r=/\s+/;this.on=function(h,f,g){if(!p(this,"on",h,[f,g])||!f)return this;this._events||(this._events={});(this._events[h]||(this._events[h]=[])).push({callback:f,context:g,ctx:g||this});return this};this.off=function(h,f,g){let d,a,b,c,k,q,e,n;if(!this._events||
!p(this,"off",h,[f,g]))return this;if(!h&&!f&&!g)return this._events=void 0,this;c=h?[h]:m.keys(this._events);k=0;for(q=c.length;k<q;k++)if(h=c[k],b=this._events[h]){d=[];this._events[h]=d;if(f||g)for(e=0,n=b.length;e<n;e++)a=b[e],(f&&f!==a.callback&&f!==a.callback._callback||g&&g!==a.context)&&d.push(a);d.length||delete this._events[h]}return this};this.once=function(h,f,g){function d(){let b=v.call(arguments);a.off(h,d,g);f.apply(this,b)}let a=this;this.on(h,d,g);return this};this.trigger=function(h){if(!this._events)return this;
let f=v.call(arguments,1);if(!p(this,"trigger",h,f))return this;let g=this._events[h],d=this._events.all;g&&l(g,f);d&&l(d,arguments);return this}}let v=Array.prototype.slice,m={isPlainObject:function(p){if("[object Object]"!==String(p)||p.nodeType||p.window&&p.window==p)return!1;try{if(p.constructor&&!Object.prototype.hasOwnProperty.call(p.constructor.prototype,"isPrototypeOf"))return!1}catch(l){return!1}return!0},keys:function(p){if(!this.isPlainObject(p))return[];let l=[];for(let r in p)Object.prototype.hasOwnProperty.call(p,
r)&&l.push(r);return l},_idCounter:0,uniqueId:function(p){let l=String(++this._idCounter);return p?p+l:l}};return{create:function(){return new t}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js",[],function(){function t(b,c,k){l||(l=c.getGlobalServices().getJsLoggingService());l[b](k)}function v(b,c,k){let q=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);k=k||{};k.pageId=h;k.referer=f;k.coreAssetsVersion=q&&q[1];let e;try{e=[c||"no message","START_JSON",JSON.stringify(k),"END_JSON"].join(" ")}catch(n){p("Failed to stringify log's json data",{exception:n});return}if(!extole.LOG_EXCLUDE_REGEX||
!e.match(extole.LOG_EXCLUDE_REGEX)){a[e]=++a[e]||1;if(g[b]>=g[extole.LOG_LEVEL_CONSOLE]&&(c=b+" "+e,window.console))if(window.console[b.toLowerCase()])window.console[b.toLowerCase()](c);else window.console.log(c);g[b]>=g[extole.LOG_LEVEL_REMOTE]&&(c=a[e],d[c]&&m(b,e+(1<c?" log count: "+c:"")))}}function m(b,c){extole.require(["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/api.js"],function(k){k.post("/api/v4/debug/logs",{level:b,message:c},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function p(b,c){v("ERROR",b,c)}let l;if("undefined"===typeof window)return{debug:function(b,c){t("debug",b,c)},info:function(b,c){t("info",b,c)},warn:function(b,c){t("warn",b,c)},error:function(b,c){t("error",b,c)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};let r=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",h=String((new Date).getTime()),f=window.location.href,g={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},d={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||r;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";let a={};return{debug:function(b,c){v("DEBUG",b,c)},info:function(b,c){v("INFO",b,c)},warn:function(b,c){v("WARN",b,c)},error:p,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/Timer.js",[],function(){return function(){let t=this,v;this.start=function(){if(v)throw Error("Timer.start has already been called");v=new Date;return t};this.getElapsedTime=function(){if(!v)throw Error("Timer has not been started");return new Date-v}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/type.js",[],function(){function t(p,l){return function(r){return v(p,r,l)}}function v(p,l,r){r=r||{};p=Object.prototype.toString.call(l)==="[object "+p+"]";l=l&&r.construct?l.constructor===r.construct:!0;return(r.negate?!p:p)&&l}let m=/\[object (Function|Array|String|Boolean|Number|Undefined|Null)\]/;return{isPlainJs:function(p){return this.isPlainObject(p)||m.test(Object.prototype.toString.call(p))},
isJavaMap:function(p){return"undefined"!==typeof Java&&Java.type?p instanceof Java.type("java.util.Map"):!1},isPlainObject:t("Object",{construct:Object}),isPlainFunction:t("Function"),isArray:t("Array"),isString:t("String"),isBoolean:t("Boolean"),isNumber:t("Number"),isUndefined:t("Undefined"),isDefined:t("Undefined",{negate:!0}),isNull:t("Null"),test:v}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js"],function(t){function v(f){let g={};(function c(a,b){for(let k in a){let q=a[k],e=(b?b+".":"")+k;"[object Object]"===Object.prototype.toString.call(q)?c(q,e):p(e)&&(g[e]=q)}})(f);return g}function m(f){try{return decodeURIComponent(f)}catch(g){return f}}function p(f){return"__proto__"!==
f&&"prototype"!==f&&"constructor"!==f}function l(f,g,d){g=(g||[]).concat("object"===typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);d=r(d||location.href);f=r(f);return(/^https?:\/\//.test(f)?t.find(g,function(a){let b=h.exec(f);return(new RegExp(a)).test(b&&b[1])}):1)?f:d}function r(f){return f.replace(RegExp("(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)","gi"),"")}let h=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(f){let g=
"";for(let d in f)g+="&"+encodeURIComponent(d)+"="+encodeURIComponent(String(f[d]));return g.replace(/^&/,"?")},deserialize:function(f){let g={};if(!f)return g;f=(f.match(/^\?/)?f.slice(1):f).split("&");for(let a=0;a<f.length;a++){var d=f[a].split("=");let b=m(d[0]);d=m(d[1]);p(b)&&(g[b]=d)}return g},objectToDotNotation:v,dotNotationToObject:function(f){let g={};f=v(f);for(let d in f){let a=g,b=d.split("."),c=b.pop();for(;b.length;){let k=b.shift();p(k)&&(a[k]=a[k]||{},a=a[k])}p(c)&&(a[c]=f[d])}return g},
decodeComponent:m,encodeComponent:function(f){return encodeURIComponent(f)},getSafeRedirectUrl:l,executeSafeRedirect:function(f,g,d){window.location.href=l(f,g,d)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/type.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js",
"https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/token-store.js"],function(t,v,m,p,l){function r(a,b){function c(){if(4===a.readyState&&!E){E=!0;var D=a.status||200;if(String(D).match(/^[23]/))"function"===typeof B?(D=k(a.getAllResponseHeaders()),D["x-extole-cookie-consent"]&&("YEAR"===D["x-extole-cookie-consent"]?l.setConsented():l.setUnconsented()),D["x-extole-token"]&&l.set(D["x-extole-token"]),B.call(a,a.responseText,a)):p.warn("'complete' callback must be a function.");
else{try{var F=JSON.parse(a.responseText)}catch(H){F=""}403!==D||"invalid_access_token"!==F.code&&"expired_access_token"!==F.code||l.remove();A.call(a,a.statusText,a.status)}n()}}function k(D){try{let F={};D.trim().split(/[\r\n]+/).forEach(H=>{var I=H.split(": ");H=I.shift();I=I.join(": ");F[H]=I});return F}catch(F){return p.error("Error parsing response headers: ",F),{}}}function q(D){E||(E=!0,p.error("Error with url "+G+"= "+u.join(","),e(D)),A.call(a,a.statusText,a.status))}function e(D){return{eventType:D&&
D.type||null,options:b,readyState:a.readyState,response:a.response,responseText:a.responseText,responseType:a.responseType,responseURL:a.responseURL,responseXML:a.responseXML,status:a.status,statusText:a.statusText,timeout:a.timeout,responseHeaders:a.getAllResponseHeaders()}}function n(D){0>G.indexOf(p.LOGGING_ENDPOINT)&&p.debug("ajax request complete",e(D))}let u=Array.prototype.slice.call(arguments),w=b.headers||{},z=b.xhrFields||{},G=b.url||"",C=b.data||"",x=(b.type||"get").toUpperCase(),B=b.complete||
function(){},A=b.error||function(){},y=l.get();G.includes("/api/")&&y&&!b.noAuthorizationHeader?w.Authorization=y:G.includes("/zones/")&&(y&&!b.noAuthorizationHeader&&(w.Authorization="Bearer+"+y),"GET"!==x&&"HEAD"!==x&&(C=h(w,C)));m.isPlainObject(C)&&("GET"===x?(G+=v.serialize(C),C=null):C=JSON.stringify(C));a.open(x,G,!0);t.merge(a,z);t.each(w,function(D,F){try{a.setRequestHeader(F,D)}catch(H){p.error("AJAX ERROR: Couldn't set request header "+F+" to "+D)}});let E=!1;a.onload=c;a.onreadystatechange=
c;a.onerror=q;a.ontimeout=q;a.onabort=n;a.send(C)}function h(a,b){function c(q){let e={};t.each(q,function(n,u){u=0<=u.indexOf(".")?'"'+u+'"':u;m.isPlainObject(n)&&(n=c(n));e[u]=n});return e}let k=[];f(a);a["content-type"]="application/x-www-form-urlencoded";b=c(b);b=t.flatten(b);t.each(a,function(q,e){"content-type"!==e.toLowerCase()&&(k.push("::headers."+e+"="+q),delete a[e])});t.each(b,function(q,e){m.isUndefined(q)||k.push(encodeURIComponent(e)+"="+(m.isNull(q)?"":encodeURIComponent(q)))});return k.join("&")}
function f(a){t.each(a,function(b,c){"content-type"===c.toLowerCase()&&delete a[c]})}function g(a){a=a||{};var b=!1;for(let c=0;c<d.length;c++){try{b=d[c]()}catch(k){continue}break}r(b,a);return b}let d=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];g.convertToFormUrlEncoded=h;g.convertToMultipartFormData=function(a,b){let c=new FormData;
t.each(b,function(k,q){c.append(q,k)});f(a);return c};return g});extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/token-store.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/event-bus.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/cookie.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/tldts.js".split(" "),
function(t,v,m,p,l,r,h){function f(){function c(){A[a.MEMORY]=A[a.MEMORY]||new e;A[a.COOKIE]=A[a.COOKIE]||new n;A[a.LOCAL_STORAGE]=A[a.LOCAL_STORAGE]||new u;extole.COOKIES_DISABLED&&(A[a.COOKIE].remove(),delete A[a.COOKIE]);extole.LOCAL_STORAGE_ALWAYS_ENABLED||extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||(A[a.LOCAL_STORAGE].remove(),delete A[a.LOCAL_STORAGE])}function k(){var y=x===d.YEAR?G():C();return(y=v.find(y,function(E){E=E.get();return!("string"!==
typeof E||"undefined"===E||"null"===E||!E.length)}))?y.get():null}function q(y,E){let D=k();if(!y&&D)y=D;else if(!y&&!D)return;let F=D!==y;x=Object.prototype.hasOwnProperty.call(d,E)&&E||(F||!x?w():x);z(x);v.each(x===d.YEAR?G():C(),function(H){H.set(y,x)});F&&B.trigger("change:access_token");D&&F&&p.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+D+", to: "+y)}function e(){let y={};this.get=function(){return y.extole_access_token};this.set=function(E){y.extole_access_token=E};this.remove=
function(){delete y.extole_access_token}}function n(){this.get=function(){return"ROOT_DOMAIN"===extole.CORE_CONFIG.cookieDomainPolicy?r("extole_domain_access_token")||r("extole_access_token"):r("extole_access_token")||r("extole_domain_access_token")};this.set=function(y,E){this.remove();a:{var D=window.location.hostname;var F;if(F="ROOT_DOMAIN"===extole.CORE_CONFIG.cookieDomainPolicy)F=D.toLowerCase(),F=!(F.endsWith("extole.com")||F.endsWith("extole.io"));if(F&&(F=h.getDomain(D))){D={name:"extole_domain_access_token",
domain:"."+F};break a}D={name:"extole_access_token",domain:"."+D}}r(D.name,y,{expires:b[E.toUpperCase()],path:"/",domain:D.domain,samesite:"strict"})};this.remove=function(){let y=window.location.hostname,E=h.getDomain(y);["extole_access_token","extole_domain_access_token"].forEach(function(D){r(D,"",{expires:-1,path:"/"});r(D,"",{expires:-1,path:"/",domain:"."+y});E&&r(D,"",{expires:-1,path:"/",domain:"."+E})})}}function u(){let y;(function(){let E="test"+(new Date).getTime();try{localStorage.setItem(E,
E),localStorage.removeItem(E)}catch(D){y=!1;return}y=!0})();this.get=function(){return y?localStorage.getItem("extole_access_token"):null};this.set=function(E){y&&localStorage.setItem("extole_access_token",E)};this.remove=function(){y&&localStorage.removeItem("extole_access_token")}}function w(){if(extole.CORE_CONFIG.isCookieConsentEnabled)switch(extole.CORE_CONFIG.cookieConsentPolicy){case g.COOKIE_CONSENT_OR_SESSION_COOKIE:return d.SESSION;case g.COOKIE_CONSENT_OR_NO_COOKIE:return d.NO_COOKIE;default:return d.NO_COOKIE}return d.YEAR}
function z(){let y=x===d.YEAR?G():C();v.each(A,function(E){0>y.indexOf(E)&&E.remove()})}function G(){let y=[a.MEMORY];Object.prototype.hasOwnProperty.call(A,a.COOKIE)&&y.push(a.COOKIE);(extole.LOCAL_STORAGE_ENABLED_WHEN_CONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&y.push(a.LOCAL_STORAGE);return y.map(function(E){return A[E]})}function C(){let y=[a.MEMORY];extole.CORE_CONFIG.cookieConsentPolicy===g.COOKIE_CONSENT_OR_SESSION_COOKIE&&Object.prototype.hasOwnProperty.call(A,a.COOKIE)&&y.push(a.COOKIE);
(extole.LOCAL_STORAGE_ENABLED_WHEN_UNCONSENTED||extole.LOCAL_STORAGE_ALWAYS_ENABLED)&&y.push(a.LOCAL_STORAGE);return y.map(function(E){return A[E]})}let x,B=l.create(),A={};c();(function(){let y=m.deserialize(window.location.search);y.extole_access_token&&q(y.extole_access_token,y.extole_access_token_type)})();this.getCurrentTokenDuration=function(){return x};this.get=k;this.set=q;this.remove=function(){x=w();v.each(A,function(y){y.remove()})};this.setConsented=function(){x="YEAR";q()};this.setUnconsented=
function(){x=w();q()};this.initializeStores=c;this.events=B}let g={COOKIE_CONSENT_DISABLED:"COOKIE_CONSENT_DISABLED",COOKIE_CONSENT_OR_SESSION_COOKIE:"COOKIE_CONSENT_OR_SESSION_COOKIE",COOKIE_CONSENT_OR_NO_COOKIE:"COOKIE_CONSENT_OR_NO_COOKIE"},d={NO_COOKIE:"NO_COOKIE",SESSION:"SESSION",YEAR:"YEAR"},a={MEMORY:"MEMORY",COOKIE:"COOKIE",LOCAL_STORAGE:"LOCAL_STORAGE"},b={YEAR:365,SESSION:null};extole.tokenStore=extole.tokenStore?extole.tokenStore:new f;return extole.tokenStore});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/program.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ajax.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(t,v,m){function p(h,f,g){m.info("Sending metric from metric registry: "+
h+" "+f+" "+g);g={metric_type:h,key:f,value:g};h={"Content-Type":"application/x-www-form-urlencoded","X-Extole-App":"javascript_sdk"};f=[t.getProtocol(),t.getProgramDomain(),"/api/v4/debug/metrics"].join("");g=v.convertToFormUrlEncoded(h,g);v({url:f,type:"POST",headers:h,data:g,xhrFields:{withCredentials:!0}})}function l(h){this.increment=function(f){p("COUNTER",h,f?f:1)}}function r(h){this.update=function(f){p("HISTOGRAM",h,f)}}return{histogram:function(h){return new r(h)},counter:function(h){return new l(h)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/tldts.js",[],function(){let t="co.uk gov.uk org.uk ac.uk me.uk ltd.uk plc.uk com.au net.au org.au gov.au edu.au asn.au id.au co.jp co.kr com.tw com.hk com.sg co.in co.th com.my com.ph co.id com.vn com.cn net.cn org.cn gov.cn com.br com.ar com.mx com.co com.pe com.cl com.ve co.za co.il com.eg co.ke com.tr co.nl com.pl com.es com.it com.fr com.de com.ru co.nz".split(" ");return{getDomain:function(v){if(!v||
"string"!==typeof v)return null;v=v.trim().toLowerCase();v.endsWith(".")&&(v=v.slice(0,-1));v=v.replace(/^https?:\/\//,"");v=v.split("@").pop();v=v.split(":")[0];v=v.split("/")[0];v=v.split("?")[0];v=v.split("#")[0];if(!v||-1===v.indexOf(".")||/^(\d{1,3}\.){3}\d{1,3}$/.test(v))return null;let m=v.split(".");if(2>m.length||m.some(function(l){return!l}))return null;if(2===m.length)return v;for(var p=0;p<t.length;p++){let l=t[p];if(v.endsWith("."+l))return p=l.split(".").length+1,m.length>=p?m.slice(-p).join("."):
v}return m.slice(-2).join(".")}}});
extole.define("ZoneBrowserContext",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js"],function(t,v){function m(r,h,f){this.getElement=function(){return f};this.getName=function(){return r};this.getData=function(){return h};this.getParameters=function(){return h}}function p(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=
function(){return extole.PROGRAM.programDomain};this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function l(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(r,h,f,g,d){let a=new m(r,h,f),b=new p,c=new l;this.getZone=function(){return a};this.getProgram=function(){return b};this.getCreativeData=function(){let k=
t.dotNotationToObject(t.deserialize(location.search)),q=t.dotNotationToObject(a.getParameters());return v.merge(k.extole_creative,q.creative)};this.getCoreConfig=function(){return c};this.getLocale=function(){return g||null};this.getContainer=function(){return d}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(t){function v(m,p,l){function r(){if(p())l();else{m();var f=setTimeout;h||(h=10);var g=500<h?500:h*=1.1;f(r,g)}}let h;r()}return function(m,p){let l=(new Date).getTime(),r=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,h=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||2E3,f=!1,g;v(function(){g=document.getElementById(m)},function(){let d=(new Date).getTime()-
l,a=!!g;a&&d>=h?t.debug("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+d+"ms, element id: "+m):!extole.isFindElementBeforeZoneRequest&&!f&&d>=r&&(f=!0,t.debug("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+d+"ms, element id: "+m));return a},function(){p(g)})}});
extole.define("ensure-element",["find-element-by-id"],function(t){function v(m){document.body?m(document.body.appendChild(document.createElement("div"))):addEventListener("DOMContentLoaded",function(){m(document.body.appendChild(document.createElement("div")))})}return function(m,p){m.element?p(m.element):m.element_id?t(m.element_id,p):v(p)}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/dom.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/type.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js ZoneBrowserContext ensure-element".split(" "),function(t,
v,m,p,l,r){function h(a,b){b=b||function(){};let c=a.name,k=f(a.data);d(c);this.resolve=function(q,e,n,u,w){r(a,function(z){a.element=z;t.clearEventListeners(a.element);z=new l(c,k,a.element,u,w);q(z);b(null,z.getZone())})}}function f(a){a=p.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}let g={},d=function(){let a={};return function(b){v.isUndefined(a[b])&&(a[b]=0);a[b]++;if(5===a[b]){b="duplicate_zone_requests : "+b;var c=p.filter(extole.q.history,function(k){return k.name&&
"createZone"===k.name});c=p.map(c,function(k){delete (k.args[0]||{}).element;return k});m.warn(b,c)}}}();return{get:function(a){if(!g[a])throw Error("Pending zone does not exist for id: "+a);return g[a]},create:function(){let a=Math.floor(1E9*Math.random()),b=0;return function(c,k){b++;let q=a+"."+b;g[q]=new h(c,k);return q}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/uri.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/collection.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/dom.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/client/program.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ajax.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/ExtoleError.js https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js pending-zone-service".split(" "),function(t,
v,m,p,l,r,h,f,g){let d=[];return function(a,b,c){function k(){let x={"Content-Type":"application/x-www-form-urlencoded",Accept:"text/javascript","X-Extole-App":"javascript_sdk"};n=G+"/zones/"+a.name;z&&(x["X-Extole-Jwt"]=z,delete w.jwt);C&&(x["X-Extole-Debug"]="true");r({url:n,type:"POST",headers:x,data:w,complete:function(B,A){var y=/^text\/html(;|$)/;let E=/^text\/plain(;|$)/;A=A.getResponseHeader("Content-Type");let D;/^text\/javascript(;|$)/.test(A)?D=B:y.test(A)?(y=document.createElement("div"),
y.innerHTML=B,D=p.queryFirst("script",y).innerHTML):E.test(A)&&!B?f.info("No content to render"):q(new h("Received invalid content type: '"+A+"'","invalid_content_type",null,"warn"));if(D){B=D;try{let F=document.currentScript||document.querySelector('script[src*="extole"]'),H=document.createElement("script");H.nonce=F&&(F.nonce||F.getAttribute("nonce"));H.textContent=B;document.head.appendChild(H);H.parentNode.removeChild(H)}catch(F){q(new h("Error in zone script - MESSAGE: "+F.message+" STACK: "+
F.stack,"zone_script_error"))}}e()},error:function(B,A){let y;try{y=JSON.parse(this.responseText)}catch(E){y={status:A||null,statusText:B||null}}q(new h(y.message||"Ajax zone request failed",y.code||null,y))},xhrFields:{withCredentials:!0}})}function q(x){let B=m.merge({originalMessage:x.message,zoneRequestUrl:n||null,zoneDefinition:a},x.data);b(new h("Problem creating zone",x.code||"zone_request_failed",B,x.logLevel||"error"));e()}function e(){"function"===typeof c&&setTimeout(c,500)}b=b||function(){};
let n;var u=v.deserialize(location.search);let w=m.merge({},a.data||a.parameters),z=a.jwt||w.jwt||u.extole_jwt,G=[l.getProtocol(),l.getProgramDomain()].join(""),C=w.debug&&"false"!==w.debug||extole.IS_DEBUG_ENABLED;extole.isPassRefererInZoneData&&(w.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(u=t.parseGlobalZoneParameters(u),w=m.merge(w,u));if(extole.createZonePrehandler&&(u=extole.createZonePrehandler(a,w),!1===u)){f.info("Zone request cancelled by prehandler");b(new h("Zone request cancelled by prehandler",
"prehandler_cancelled",{zoneDefinition:a},"info"));e();return}a.element_id&&(w.element_id=a.element_id);(function(){let x=Date.now(),B=x-6E4;d=d.filter(function(A){return A>B});60<d.length?f.warn("Zone request "+a.name+" exceeded maximum number of zone requests per minute: 60"):d.push(x);a.data=w;w.zone_id=g.create(a,b);w=m.flatten(w);k()})()}});
extole.define("create-zone-executor",["create-zone","ensure-element","https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/common/logger.js"],function(t,v,m){function p(d,a,b){function c(e,n){e?k(e):(f=!0,a&&a(null,n),q())}function k(e){function n(){setTimeout(function(){l(d,a,b)},1)}b+=1;let u="prehandler_cancelled"!==e.code;if(u&&5>b)n();else{if(u)m[e.logLevel||"error"](e.toString());a&&a(e)}}let q;h.push(function(e){q=r(e);t(d,c,q);f&&q()})}function l(d,a,b){function c(){let k=
!!d.element;extole.isFindElementBeforeZoneRequest&&!k||p(d,a,b)}b=Number(b)||0;extole.isFindElementBeforeZoneRequest?v(d,function(k){d.element=k;c()}):c()}function r(d){let a=!1;return function(){let b=Array.prototype.slice.call(arguments);a||(a=!0,d.apply(null,b))}}let h=new function(){let d=0,a=[],b=this,c=!1;this.push=function(k){a.push(k);this.next()};this.next=function(){function k(){d--;f=!0;b.next()}if(!c)for(;1>d&&a.length;)g||f||this.next(),g=!1,a.shift()(k),d++};this.start=function(){c=
!1;this.next()};this.stop=function(){c=!0}},f=!1,g=!0;return{initiateExecution:l}});
extole.define("https://origin.xtlo.net/type=core:clientId=1816143665:coreAssetsVersion=1544591110545/legacy-tag-scanning-service.js",[],function(){var t={};t.validators=function(){return{isEmail:function(m){m=String(m);m=m.replace(/^\s+/,"").replace(/\s+$/,"");return m.match(/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i)}}}();t.logger=
function(){(function(m,p,l,r,h){m[p]=m[p]||{};for(m[p].q=m[p].q||[];h<r.length;)l(r[h++],m[p])})(window,"extole",function(m,p){p[m]=p[m]||function(){p.q.push([m,arguments])}},["log"],0);return{debug:function(m,p){window.extole.log("DEBUG",m,p)},info:function(m,p){window.extole.log("INFO",m,p)},warn:function(m,p){window.extole.log("WARN",m,p)},error:function(m,p){window.extole.log("ERROR",m,p)}}}();t["utils-collections"]=function(){function m(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function p(a){if(!r(a))return[];
var b=[],c;for(c in a)m(a,c)&&b.push(c);return b}function l(a){for(var b=p(a),c=b.length,k=Array(c),q=0;q<c;q++)k[q]=a[b[q]];return k}function r(a){if("[object Object]"!==String(a)||a.nodeType||a.window&&a.window==a)return!1;try{if(a.constructor&&!Object.prototype.hasOwnProperty.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}return!0}function h(a){return a instanceof Array}function f(a,b){var c;if(a.length===Number(a.length))for(c=0;c<a.length;c++){var k=b(a[c],c);if(!1===
k)return!1}else for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)&&(k=b(a[c],c),!1===k))return!1}function g(a,b){var c=[];f(a,function(k,q){k=b(k,q);void 0!==k&&c.push(k)});return c}var d=Array.prototype.slice;f.BREAK=!1;return{each:f,map:g,mapObj:function(a,b){var c={};f(a,function(k,q){k=b(k,q);void 0!==k&&(k.key&&k.value?c[k.key]=k.value:c[q]=k)});return c},has:m,keys:p,values:l,invert:function(a){for(var b={},c=p(a),k=0,q=c.length;k<q;k++)b[a[c[k]]]=c[k];return b},toArray:function(a){return a?
h(a)?d.call(a):a.length===Number(a.length)?g(a,function(b){return b}):l(a):[]},inArray:function(a,b,c){if(b){var k=b.length;for(c=c?0>c?Math.max(0,k+c):c:0;c<k;c++)if(c in b&&b[c]===a)return c}return-1},isArray:h,isPlainObject:r}}();t.JSON=function(){var m;"object"!==typeof m&&(m={});(function(){function p(c){return 10>c?"0"+c:c}function l(c){d.lastIndex=0;return d.test(c)?'"'+c.replace(d,function(k){var q=a[k];return"string"===typeof q?q:"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)})+'"':
'"'+c+'"'}function r(c,k){var q=h,e=k[c];e&&e instanceof Date&&(e=isFinite(e.valueOf())?e.getUTCFullYear()+"-"+p(e.getUTCMonth()+1)+"-"+p(e.getUTCDate())+"T"+p(e.getUTCHours())+":"+p(e.getUTCMinutes())+":"+p(e.getUTCSeconds())+"Z":null);"function"===typeof g&&(e=g.call(k,c,e));switch(typeof e){case "string":return l(e);case "number":return isFinite(e)?String(e):"null";case "boolean":case "null":return String(e);case "object":if(!e)return"null";h+=f;var n=[];if("[object Array]"===Object.prototype.toString.apply(e)){var u=
e.length;for(c=0;c<u;c+=1)n[c]=r(c,e)||"null";k=0===n.length?"[]":h?"[\n"+h+n.join(",\n"+h)+"\n"+q+"]":"["+n.join(",")+"]";h=q;return k}if(g&&"object"===typeof g)for(u=g.length,c=0;c<u;c+=1){if("string"===typeof g[c]){var w=g[c];(k=r(w,e))&&n.push(l(w)+(h?": ":":")+k)}}else for(w in e)Object.prototype.hasOwnProperty.call(e,w)&&(k=r(w,e))&&n.push(l(w)+(h?": ":":")+k);k=0===n.length?"{}":h?"{\n"+h+n.join(",\n"+h)+"\n"+q+"}":"{"+n.join(",")+"}";h=q;return k}}var h,f,g;if("function"!==typeof m.stringify){var d=
/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;var a={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};m.stringify=function(c,k,q){var e;f=h="";if("number"===typeof q)for(e=0;e<q;e+=1)f+=" ";else"string"===typeof q&&(f=q);if((g=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("JSON.stringify");return r("",{"":c})}}if("function"!==typeof m.parse){var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;
m.parse=function(c,k){function q(e,n){var u,w=e[n];if(w&&"object"===typeof w)for(u in w)if(Object.prototype.hasOwnProperty.call(w,u)){var z=q(w,u);void 0!==z?w[u]=z:delete w[u]}return k.call(e,n,w)}c=String(c);b.lastIndex=0;b.test(c)&&(c=c.replace(b,function(e){return"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(c.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,
"")))return c=eval("("+c+")"),"function"===typeof k?q({"":c},""):c;throw new SyntaxError("JSON.parse");}}})();return m}();t.utils=function(m,p){function l(x){return x&&"function"===typeof x&&x.call&&x.apply}function r(){p.debug.apply(null,arguments)}function h(x,B){B||(B=x,x="undefined");B=Error("TYPE: "+x+"  MESSAGE: "+B);B.type=x;return B}var f=m.each,g=m.map,d=m.mapObj,a=m.has,b=m.keys,c=m.values,k=m.invert,q=m.toArray,e=m.inArray,n=m.isArray,u=m.isPlainObject,w=0;"undefined"!==typeof window.console&&
(extole.console=extole.console||console);var z=function(){var x,B,A=arguments[0]||{},y=1,E=arguments.length,D=!1;"boolean"===typeof A&&(D=A,A=arguments[1]||{},y=2);for("object"===typeof A||l(A)||(A={});y<E;y++){var F=arguments[y];if(null!==F)for(x in F){var H=A[x];var I=F[x];A!==I&&(D&&I&&(u(I)||(B=n(I)))?(B?(B=!1,H=H&&n(H)?H:[]):H=H&&u(H)?H:{},A[x]=z(D,H,I)):void 0!==I&&(A[x]=I))}}return A};var G=Array.prototype.slice;r.debug=p.debug;r.warn=p.warn;r.info=p.info;r.error=p.error;var C=extole.generalReady;
extole.generalReady||(C=extole.generalReady=function(x){function B(y){y||C.readies[A].ready?C.readies[A].funcs.push(y):(C.readies[A].ready=!0,r.debug("** generalReady ** "+A+" - set ready"));if(C.readies[A].ready)for(;y=C.readies[A].funcs.pop();)setTimeout(y,0)}extole._generalReadyAnonKey||(extole._generalReadyAnonKey=0);var A=extole._generalReadyAnonKey++;x=z(x||{},{readyTest:void 0});C.readies[A]||(C.readies[A]={ready:!1,funcs:[]});B.unset=function(){C.readies[A].ready=!1};B.set=function(){B()};
B.isReady=function(){return C.readies[A].ready};return B},C.readies={});return{uniqueId:function(x){var B=String(++w);return x?x+B:B},each:f,map:g,mapObj:d,has:a,keys:b,values:c,invert:k,toArray:q,inArray:e,isEmpty:function(x){if(null===x)return!0;if(n(x)||"string"===typeof x)return 0===x.length;for(var B in x)if(a(x,B))return!1;return!0},isArray:n,isPlainObject:u,isFunction:l,proxy:function(x,B){if(x.__proxiedContext===B)var A=x;else A=function(){return x.apply(B,arguments)},A.__proxiedContext=B;
return A},log:r,generalReady:C,extend:z,defaults:function(x){f(G.call(arguments,1),function(B){if(B)for(var A in B)void 0===x[A]&&(x[A]=B[A])});return x},createObject:Object.create||function(x){function B(){}B.prototype=x;return new B},typedError:h,throwError:function(x,B){throw h(x,B);},handleError:function(x,B,A){A=A||function(){};try{B()}catch(y){if(y.type==x)return A(y),y;throw y;}},location:{serialize:function(x){var B="";f(x,function(A,y){void 0!==y&&void 0!==A&&(B+="&"+encodeURIComponent(y)+
"="+encodeURIComponent(String(A)))});0<B.length&&(B="?"+B.slice(1));return B},deserialize:function(x){if(!x)return{};var B={};x=x.substring(1).split("&");for(var A=0;A<x.length;A++){var y=x[A],E=y.substring(0,y.indexOf("="));y=y.substring(y.indexOf("=")+1);if(E&&y)try{B[E]=decodeURIComponent(y)}catch(D){r("Bad Query Param "+E+" : "+y)}}return B}}}}(t["utils-collections"],t.logger);t.params=function(m,p){var l={e:"email",f:"first_name",l:"last_name"},r="email first_name last_name source partner_conversion_id partner_user_id".split(" ");
return{rekey:function(h){var f={};m.each(h,function(g,d){l[d]&&(d=l[d]);var a=/^tag:/.test(d),b=-1<m.inArray(d,r);a||b||(d="tag:"+d);f[d]=g});return f},split:function(h,f){f=m.extend({validateEmail:!0},f||{});var g={init:{},client:{}};if(!h)return g;m.each(h,function(d,a){var b=g.init;-1<a.indexOf("tag:")?(a=a.substring(4),b=g.client):"email"==a&&f.validateEmail&&!p.isEmail(d)&&(m.log("Initialized with invalid email address ("+d+") - (configUtils.getInitParams)"),d=void 0);b[a]=d});return g},removeTags:function(h){var f=
{};m.each(h,function(g,d){d=d.replace(/^tag:/,"");f[d]=g});return f}}}(t.utils,t.validators);t["event-bus"]=function(){function m(){function r(g,d,a,b){if(!a)return!0;if("object"===typeof a){for(var c in a)g[d].apply(g,[c,a[c]].concat(b));return!1}if(f.test(a)){a=a.split(f);c=0;for(var k=a.length;c<k;c++)g[d].apply(g,[a[c]].concat(b));return!1}return!0}function h(g,d){var a,b=-1,c=g.length,k=d[0],q=d[1],e=d[2];switch(d.length){case 0:for(;++b<c;){(a=g[b]).callback.call(a.ctx);return}case 1:for(;++b<
c;){(a=g[b]).callback.call(a.ctx,k);return}case 2:for(;++b<c;){(a=g[b]).callback.call(a.ctx,k,q);return}case 3:for(;++b<c;){(a=g[b]).callback.call(a.ctx,k,q,e);return}default:for(;++b<c;){(a=g[b]).callback.apply(a.ctx,d);break}}}this._events={};var f=/\s+/;this.on=function(g,d,a){if(!r(this,"on",g,[d,a])||!d)return this;this._events||(this._events={});(this._events[g]||(this._events[g]=[])).push({callback:d,context:a,ctx:a||this});return this};this.off=function(g,d,a){var b,c,k,q;if(!this._events||
!r(this,"off",g,[d,a]))return this;if(!g&&!d&&!a)return this._events=void 0,this;var e=g?[g]:l.keys(this._events);var n=0;for(k=e.length;n<k;n++)if(g=e[n],c=this._events[g]){this._events[g]=b=[];if(d||a){var u=0;for(q=c.length;u<q;u++){var w=c[u];(d&&d!==w.callback&&d!==w.callback._callback||a&&a!==w.context)&&b.push(w)}}b.length||delete this._events[g]}return this};this.once=function(g,d,a){function b(){var k=p.call(arguments);d.apply(this,k);c.off(g,b,a)}var c=this;this.on(g,b,a);return this};this.trigger=
function(g){if(!this._events)return this;var d=p.call(arguments,1);if(!r(this,"trigger",g,d))return this;var a=this._events[g],b=this._events.all;a&&h(a,d);b&&h(b,arguments);return this}}var p=Array.prototype.slice,l={isPlainObject:function(r){if("[object Object]"!==String(r)||r.nodeType||r.window&&r.window==r)return!1;try{if(r.constructor&&!Object.prototype.hasOwnProperty.call(r.constructor.prototype,"isPrototypeOf"))return!1}catch(h){return!1}return!0},keys:function(r){if(!this.isPlainObject(r))return[];
var h=[],f;for(f in r)Object.prototype.hasOwnProperty.call((Object.prototype,r,f))&&h.push(f);return h},_idCounter:0,uniqueId:function(r){var h=String(++this._idCounter);return r?r+h:h}};return{create:function(){return new m}}}();t["zone-event-bus"]=function(m){var p=m.create();return{publish:function(l,r,h){Array.prototype.slice.call(arguments);p.trigger("zone",l,r,h)},subscribe:function(l){p.on("zone",l)}}}(t["event-bus"]);t["zone-convert"]=function(m,p,l){function r(h){var f=h.code||"",g=h.description||
"";this.stack=Error(g).stack;this.getCode=function(){return f};this.getDescription=function(){return g}}r.prototype=Error();r.prototype.constructor=r;return function(h,f){f=f||function(){};var g=function(a){a=(a||"").toLowerCase();if("purchase"===a)var b="conversion";else if("register"===a||"registration"===a)b="registration";return b||null}(h.type),d=function(a){a=p.rekey(a);return p.removeTags(a)}(h.parameters||{});if(!g)return h="Error: could not find zone based on type:"+h.type,l.error(h),h=new r({description:h,
code:"error-no-type"}),f(h);m.publish(g,null,d)}}(t["zone-event-bus"],t.params,t.logger);t["dom-ready"]=function(m){var p=m.generalReady();(function(){var l;document.addEventListener?l=function(){document.removeEventListener("DOMContentLoaded",l,!1);p.set()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),p.set())});"complete"===document.readyState&&p.set();document.addEventListener?(document.addEventListener("DOMContentLoaded",l,
!1),window.addEventListener("load",p.set,!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",l),window.attachEvent("onload",p.set))})();return p}(t.utils);t["dom-query"]=function(){return function(m,p){return(p||document).querySelectorAll(m)}}();t["page-scanner"]=function(m,p,l){function r(){function d(){b||(k=!1,b=!0,setTimeout(function(){for(var q={},e=c.splice(0,c.length);0<e.length;){var n=e.shift(),u=q[n.selector];if(!u)try{u=l(n.selector)}catch(w){m.log.error("query error -"+
n.selector)}u&&0<u.length&&n.withElements(u);n.shouldDelete()||c.push(n)}b=!1;k?d():f||(q=Math.ceil(50*(.3*Math.pow(1.017,a/50)+.7)),setTimeout(d,q),a=q)},1))}var a=0,b=!1,c=[],k=!1;this.queue=function(q){c.push(q);k=!0;b||d()};this.scan=d}function h(d){function a(){return!0}function b(){}var c=0,k=!1;this.withElements=function(q){m.each(q,function(e){a(e)&&b(e)});c++};this.setFilter=this.andIts=function(q){a=q;return this};this.setCompleted=this.thenCall=function(q){b=q;return this};this.setDeleteAfterCall=
this.andRemove=function(){k=!0};this.shouldDelete=function(){return 0<c&&!0===k?!0:!1};this.selector=d}var f=!1;p(function(){f=!0});var g=new r;return{whenYouFind:function(d){var a=new h(d);setTimeout(function(){g.queue(a)},1);return a},findAllTheThings:function(){g.scan()},reset:function(){g=new r}}}(t.utils,t["dom-ready"],t["dom-query"]);t["config-utils"]=function(m,p){return{getSharedVars:function(){for(var l=document.getElementsByTagName("script"),r={},h,f=0;f<l.length;f++)if("extole/context"==
l[f].type){h=void 0;try{h=m.parse(l[f].innerHTML)}catch(g){p.log.error("Bad JSON in context script tag.")}h&&p.extend(r,h)}return r}}}(t.JSON,t.utils);t["creative-placement"]=function(m,p){function l(f,g){"none"!==g&&(f=document.createElement("span"));return f}function r(f,g,d,a){var b=arguments,c=g.parentNode;if(!c)return p(function(){c||(document.body.appendChild(g),r.apply(null,b))}),!1;"replace"==d?(c.insertBefore(f,g),c.removeChild(g)):"before"==d?c.insertBefore(f,g):"after"==d?g.nextSibling?
c.insertBefore(f,g.nextSibling):c.appendChild(f):"inside"==d&&g.appendChild(f);a(null)}function h(f){f=m.extend({insertPosition:void 0,referenceElement:void 0},f||{});var g=f.insertPosition;f=f.referenceElement;g||(g="before","*"==f?g="inside":f&&(g="none"));return g}return{renderElement:function(f,g){var d=f.getData();d=h({insertPosition:d.insert_position,referenceElement:d.reference_element});f=f.element;var a=l(f,d);r(a,f,d,function(){g(null,a)});return a},getInsertPosition:h}}(t.utils,t["dom-ready"]);
t["zone-factory"]=function(m,p){function l(f){var g=f||{};!0!==g.__created&&(g=m.createObject(h),m.extend(g,f),r.push(g),g.__created=!0);return g}var r=[],h={elementReady:function(f){var g=this;p.renderElement(this,function(d,a){g.element=a;f&&f(d,a)})},shouldShowDefaultContent:function(){return!1},renderDefaultContent:function(){},getConfig:function(){return{}},getInsertPosition:function(){return p.getInsertPosition({insertPosition:this.data.insert_position,referenceElement:this.data.reference_element})},
getData:function(){return this.data},getType:function(){return this.type||"cta"},getName:function(){return this.name&&this.name.toLowerCase()},getParameters:function(){return m.extend({},this.data.parameters,this.data.params)},removeCampaignReferences:function(){this.data.parameters&&delete this.data.parameters.campaign_id;this.data.params&&delete this.data.params.campaign_id;this.campaign&&delete this.campaign},destroy:function(){this.element&&this.element.parentNode&&this.element.parentNode.removeChild(this.element);
for(var f=0;f<r.length&&r[f]!=this;f++);r.splice(f,1)}};m.extend(l,{getZones:function(){return r}});return l}(t.utils,t["creative-placement"]);t["zones-requester"]=function(m,p,l,r,h,f){function g(d){function a(b,c){c=c||function(){};b=b.reference_element&&"*"==b.reference_element?"body":b.reference_element?b.reference_element:!1;if(!b)return c(null,d);r.whenYouFind(b).thenCall(function(k){c(null,k)}).andRemove()}this.prepare=function(b){b=b||function(){};try{var c=m.parse(d.innerHTML)}catch(e){return b(Error("element has bad JSON, can't make zone. html: "+
d.innerHTML))}var k=(c.zone||"default").toLowerCase(),q=p.extend(!0,{},c);a(q,function(e,n){if(e)return b(e);b(null,k,{id:{}.id,element:n,data:q})})}}return new function(){function d(){b||r.whenYouFind('script[type="extole/widget"]').thenCall(function(c){c.hasBeenUsed||(c.hasBeenUsed=!0,(new g(c)).prepare(function(k,q,e){if(k)return p.log("couldn't prepare page request "+k.message);a(q,e)}))});b=!0;r.findAllTheThings()}function a(c,k){k=k||{};var q=h(p.extend({name:c,type:c},k));q.elementReady(function(e,
n){e=q.getName();var u=q.getParameters();q.campaign&&(u.campaign_id=q.campaign.id);f.publish(e,n,u)})}var b=!1;this.start=function(){d()};this.request=a}}(t.JSON,t.utils,t["dom-ready"],t["page-scanner"],t["zone-factory"],t["zone-event-bus"]);t.zones={requester:t["zones-requester"]};var v=new function(){function m(){p.whenYouFind('script[type="extole/conversion"]').thenCall(function(b){if(!b.hasBeenUsed){b.hasBeenUsed=!0;a:{var c={};try{c=r.parse(b.innerHTML)}catch(k){h.log.error("Could not fire conversion. "+
k);break a}b=c.type||c.event_type;c=h.extend(!0,{},g.getSharedVars(),c);f({type:b,parameters:c.params})}}}).andRemove();p.findAllTheThings()}var p=t["page-scanner"],l=t.zones,r=t.JSON,h=t.utils,f=t["zone-convert"],g=t["config-utils"],d=t["zone-event-bus"],a=!1;this.start=function(){if(a)throw Error("legacy-tag-scanning service has already been started");a=!0;l.requester.start();m();d.subscribe(function(b,c,k){extole.createZone({name:b,element:c,data:k})})}};v.start();return v});